### ISSUE TITLE
container as parent_cmd instead of mode

### ISSUE THREAD

**Issue by Ali-aqrabawi** [okda-networks/onm-cli#54]
container as parent_cmd instead of mode

**Comment by Ali-aqrabawi** [comment]
This is need recheck, for example the `vrrp` and `ipv4` under interface.

In this case we should have on single cmd:

```
interfaces
  interface x
    ipv4 addresses x.x.x.x subnet 24

    vrrp priority x
    vrrp group x
```

**Comment by adaraiseh** [comment]
Similar example would be skipping choice 
Example:
acls
   acl <name>
     aces <-- skipped as you suggested
        ace <name>
          matches <-- skipped as suggested
             L2 <-- this choice also should be skipped
               eth <-- should be be skipped as you suggested
                 src_mac 11:22:33:44:55:66
