### ISSUE TITLE
change print command to show

### ISSUE THREAD

**Issue by adaraiseh** [okda-networks/onm-cli#63]
in later version releases, print command should be changed to show and should display cli like commands formatted data.
also it should incorporate children commands to show modules operational data outputs.
example commands:
```
show running-config                                    <- global running config
show interfaces running-config                         <- specific module running config
show interfaces summary                                <- operational data summary
show interfaces interface <name> running-config        <- specific list element config
show interfaces interface <name> details               <- specific list operational element data
```

**Comment by Ali-aqrabawi** [comment]
This needs discussion. We have two types of data to show; oper-data and config-data. 

- show config <_yang-specific-tree_>
- show <_yang-specific-tree_> // for operational
